In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
import pandas as pd
df=pd.read_csv(r"/content/sample_data/cars_price.csv")

In [ ]:
df.head()

symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3                 ?  alfa-romero       gas        std          two   
1          3                 ?  alfa-romero       gas        std          two   
2          1                 ?  alfa-romero       gas        std          two   
3          2               164         audi       gas        std         four   
4          2               164         audi       gas        std         four   

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   

   fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
0         mpfi  3.47    2.68               9.0        111      5000       21   
1         mpfi  3.47    2.68               9.0        111      5000       21   
2         mpfi  2.68    3.47               9.0        154      5000       19   
3         mpfi  3.19     3.4              10.0        102      5500       24   
4         mpfi  3.19     3.4               8.0        115      5500       18   

  highway-mpg  price  
0          27  13495  
1          27  16500  
2          26  16500  
3          30  13950  
4          22  17450  

[5 rows x 26 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    object 
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   aspiration         205 non-null    object 
 5   num-of-doors       205 non-null    object 
 6   body-style         205 non-null    object 
 7   drive-wheels       205 non-null    object 
 8   engine-location    205 non-null    object 
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64  
 14  engine-type        205 non-null    object 
 15  num-of-cylinders   205 non-null    object 
 16  engine-size        205 non

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [ ]:
df.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

In [ ]:
df.describe()

symboling  wheel-base      length       width      height  \
count  205.000000  205.000000  205.000000  205.000000  205.000000   
mean     0.834146   98.756585  174.049268   65.907805   53.724878   
std      1.245307    6.021776   12.337289    2.145204    2.443522   
min     -2.000000   86.600000  141.100000   60.300000   47.800000   
25%      0.000000   94.500000  166.300000   64.100000   52.000000   
50%      1.000000   97.000000  173.200000   65.500000   54.100000   
75%      2.000000  102.400000  183.100000   66.900000   55.500000   
max      3.000000  120.900000  208.100000   72.300000   59.800000   

       curb-weight  engine-size  compression-ratio    city-mpg  highway-mpg  
count   205.000000   205.000000         205.000000  205.000000   205.000000  
mean   2555.565854   126.907317          10.142537   25.219512    30.751220  
std     520.680204    41.642693           3.972040    6.542142     6.886443  
min    1488.000000    61.000000           7.000000   13.000000    16.000000  
25%    2145.000000    97.000000           8.600000   19.000000    25.000000  
50%    2414.000000   120.000000           9.000000   24.000000    30.000000  
75%    2935.000000   141.000000           9.400000   30.000000    34.000000  
max    4066.000000   326.000000          23.000000   49.000000    54.000000

In [ ]:
df.nunique()

symboling              6
normalized-losses     52
make                  22
fuel-type              2
aspiration             2
num-of-doors           3
body-style             5
drive-wheels           3
engine-location        2
wheel-base            53
length                75
width                 44
height                49
curb-weight          171
engine-type            7
num-of-cylinders       7
engine-size           44
fuel-system            8
bore                  39
stroke                37
compression-ratio     32
horsepower            60
peak-rpm              24
city-mpg              29
highway-mpg           30
price                187
dtype: int64

In [ ]:
df.shape

(205, 26)

In [ ]:
df.iloc[:,-1].value_counts()

?        4
8921     2
18150    2
8845     2
8495     2
        ..
45400    1
16503    1
5389     1
6189     1
22625    1
Name: price, Length: 187, dtype: int64

In [ ]:
for i in df.columns:
    print(f'{i},{df[i].value_counts()}')

symboling, 0    67
 1    54
 2    32
 3    27
-1    22
-2     3
Name: symboling, dtype: int64
normalized-losses,?      41
161    11
91      8
150     7
134     6
128     6
104     6
85      5
94      5
65      5
102     5
74      5
168     5
103     5
95      5
106     4
93      4
118     4
148     4
122     4
83      3
125     3
154     3
115     3
137     3
101     3
119     2
87      2
89      2
192     2
197     2
158     2
81      2
188     2
194     2
153     2
129     2
108     2
110     2
164     2
145     2
113     2
256     1
107     1
90      1
231     1
142     1
121     1
78      1
98      1
186     1
77      1
Name: normalized-losses, dtype: int64
make,toyota           32
nissan           18
mazda            17
mitsubishi       13
honda            13
volkswagen       12
subaru           12
peugot           11
volvo            11
dodge             9
mercedes-benz     8
bmw               8
audi              7
plymouth          7
saab              6
porsche           5
isuzu

In [ ]:
import numpy as np
df.replace('?', np.nan, inplace = True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  164 non-null    object 
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   aspiration         205 non-null    object 
 5   num-of-doors       203 non-null    object 
 6   body-style         205 non-null    object 
 7   drive-wheels       205 non-null    object 
 8   engine-location    205 non-null    object 
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64  
 14  engine-type        205 non-null    object 
 15  num-of-cylinders   205 non-null    object 
 16  engine-size        205 non

In [ ]:
df['price']=pd.to_numeric(df['price'])
df['normalized-losses']=pd.to_numeric(df['normalized-losses'])
df['bore']=pd.to_numeric(df['bore'])
df['stroke']=pd.to_numeric(df['stroke'])
df['horsepower']=pd.to_numeric(df['horsepower'])
df['peak-rpm']=pd.to_numeric(df['peak-rpm'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  164 non-null    float64
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   aspiration         205 non-null    object 
 5   num-of-doors       203 non-null    object 
 6   body-style         205 non-null    object 
 7   drive-wheels       205 non-null    object 
 8   engine-location    205 non-null    object 
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64  
 14  engine-type        205 non-null    object 
 15  num-of-cylinders   205 non-null    object 
 16  engine-size        205 non

In [ ]:
# Handling null values
df.isnull().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [ ]:
# Handling missing values in Numeric Column
from sklearn.impute import SimpleImputer
import numpy as np

SI = SimpleImputer(strategy='mean', missing_values=np.nan)
df['normalized-losses'] = SI.fit_transform(df[['normalized-losses']])
df['horsepower'] = SI.fit_transform(df[['horsepower']])
df['bore'] = SI.fit_transform(df[['bore']])
df['stroke'] = SI.fit_transform(df[['stroke']])
df['horsepower'] = SI.fit_transform(df[['horsepower']])
df['peak-rpm'] = SI.fit_transform(df[['peak-rpm']])
df['price'] = SI.fit_transform(df[['price']])

In [ ]:
df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         2
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [ ]:
# Handling missing values in Categorical column
from sklearn.impute import SimpleImputer
import numpy as np

SI = SimpleImputer(strategy='most_frequent', missing_values=np.nan)
df['num-of-doors'] = SI.fit_transform(df[['num-of-doors']])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    float64
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   aspiration         205 non-null    object 
 5   num-of-doors       205 non-null    object 
 6   body-style         205 non-null    object 
 7   drive-wheels       205 non-null    object 
 8   engine-location    205 non-null    object 
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64  
 14  engine-type        205 non-null    object 
 15  num-of-cylinders   205 non-null    object 
 16  engine-size        205 non

In [ ]:
df['make'].value_counts()

toyota           32
nissan           18
mazda            17
mitsubishi       13
honda            13
volkswagen       12
subaru           12
peugot           11
volvo            11
dodge             9
mercedes-benz     8
bmw               8
audi              7
plymouth          7
saab              6
porsche           5
isuzu             4
jaguar            3
chevrolet         3
alfa-romero       3
renault           2
mercury           1
Name: make, dtype: int64

In [ ]:
df['fuel-type'].value_counts()

gas       185
diesel     20
Name: fuel-type, dtype: int64

In [ ]:
df['aspiration'].value_counts()

std      168
turbo     37
Name: aspiration, dtype: int64

In [ ]:
df['body-style'].value_counts()

sedan          96
hatchback      70
wagon          25
hardtop         8
convertible     6
Name: body-style, dtype: int64

In [ ]:
df['num-of-cylinders'].value_counts()

four      159
six        24
five       11
eight       5
two         4
three       1
twelve      1
Name: num-of-cylinders, dtype: int64

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
OE=OrdinalEncoder()

In [ ]:
df['make']=OE.fit_transform(df[['make']])
df['fuel-type']=OE.fit_transform(df[['fuel-type']])
df['aspiration']=OE.fit_transform(df[['aspiration']])
df['body-style']=OE.fit_transform(df[['body-style']])
df['num-of-cylinders']=OE.fit_transform(df[['num-of-cylinders']])
df['num-of-doors']=OE.fit_transform(df[['num-of-doors']])
df['drive-wheels']=OE.fit_transform(df[['drive-wheels']])
df['engine-type']=OE.fit_transform(df[['engine-type']])
df['fuel-system']=OE.fit_transform(df[['fuel-system']])
df['engine-location']=OE.fit_transform(df[['engine-location']])
df

symboling  normalized-losses  make  fuel-type  aspiration  num-of-doors  \
0            3              122.0   0.0        1.0         0.0           1.0   
1            3              122.0   0.0        1.0         0.0           1.0   
2            1              122.0   0.0        1.0         0.0           1.0   
3            2              164.0   1.0        1.0         0.0           0.0   
4            2              164.0   1.0        1.0         0.0           0.0   
..         ...                ...   ...        ...         ...           ...   
200         -1               95.0  21.0        1.0         0.0           0.0   
201         -1               95.0  21.0        1.0         1.0           0.0   
202         -1               95.0  21.0        1.0         0.0           0.0   
203         -1               95.0  21.0        0.0         1.0           0.0   
204         -1               95.0  21.0        1.0         1.0           0.0   

     body-style  drive-wheels  engine-location  wheel-base  ...  engine-size  \
0           0.0           2.0              0.0        88.6  ...          130   
1           0.0           2.0              0.0        88.6  ...          130   
2           2.0           2.0              0.0        94.5  ...          152   
3           3.0           1.0              0.0        99.8  ...          109   
4           3.0           0.0              0.0        99.4  ...          136   
..          ...           ...              ...         ...  ...          ...   
200         3.0           2.0              0.0       109.1  ...          141   
201         3.0           2.0              0.0       109.1  ...          141   
202         3.0           2.0              0.0       109.1  ...          173   
203         3.0           2.0              0.0       109.1  ...          145   
204         3.0           2.0              0.0       109.1  ...          141   

     fuel-system  bore  stroke  compression-ratio  horsepower  peak-rpm  \
0            5.0  3.47    2.68                9.0       111.0    5000.0   
1            5.0  3.47    2.68                9.0       111.0    5000.0   
2            5.0  2.68    3.47                9.0       154.0    5000.0   
3            5.0  3.19    3.40               10.0       102.0    5500.0   
4            5.0  3.19    3.40                8.0       115.0    5500.0   
..           ...   ...     ...                ...         ...       ...   
200          5.0  3.78    3.15                9.5       114.0    5400.0   
201          5.0  3.78    3.15                8.7       160.0    5300.0   
202          5.0  3.58    2.87                8.8       134.0    5500.0   
203          3.0  3.01    3.40               23.0       106.0    4800.0   
204          5.0  3.78    3.15                9.5       114.0    5400.0   

     city-mpg  highway-mpg    price  
0          21           27  13495.0  
1          21           27  16500.0  
2          19           26  16500.0  
3          24           30  13950.0  
4          18           22  17450.0  
..        ...          ...      ...  
200        23           28  16845.0  
201        19           25  19045.0  
202        18           23  21485.0  
203        26           27  22470.0  
204        19           25  22625.0  

[205 rows x 26 columns]

In [ ]:
X = df.iloc[:, :-1]
Y = df.iloc[:, -1]

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state=2)

In [ ]:
x_train.shape


(143, 25)

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(x_train)
std_xtrain = ss.transform(x_train)
std_xtest = ss.transform(x_test)

In [ ]:
#Lasso
results = []
from sklearn.linear_model import Lasso
model = Lasso(alpha = 0.05, positive = True, max_iter = 100000)
model.fit(std_xtrain, y_train)

from sklearn.metrics import mean_absolute_error
print("With all the 8 features", mean_absolute_error(y_test, model.predict(std_xtest)))
results.append(mean_absolute_error(y_test, model.predict(std_xtest)))

With all the 8 features 2279.777309419742


In [ ]:
from sklearn.feature_selection import RFE
model = Lasso(alpha = 0.05, positive = True, max_iter = 100000)
rfe = RFE(model, n_features_to_select = 15)
rfe.fit(std_xtrain, y_train)

RFE(estimator=Lasso(alpha=0.05, max_iter=100000, positive=True),
    n_features_to_select=15)

In [ ]:
rfe.ranking_


array([ 1,  9,  8,  7,  1,  1,  6,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        3,  4,  5,  1, 10,  1,  2, 11])

In [ ]:
rfe.support_

array([ True, False, False, False,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True, False, False])

In [ ]:
std_xtrain[:,rfe.support_]

array([[ 0.90034639, -0.51525404,  1.1110243 , ..., -0.8372724 ,
        -0.19600834,  0.7165901 ],
       [ 0.90034639, -0.51525404,  1.1110243 , ...,  0.1719456 ,
        -0.41940786,  0.7165901 ],
       [-2.25915138,  1.94079022, -0.90007032, ...,  0.03432496,
        -0.66762955, -0.11399891],
       ...,
       [ 1.69022084, -0.51525404,  1.1110243 , ...,  2.41974931,
        -0.4690522 , -0.84076429],
       [-0.67940249, -0.51525404, -0.90007032, ...,  1.84633   ,
        -0.5435187 ,  0.50894285],
       [ 0.90034639, -0.51525404,  1.1110243 , ...,  0.40131332,
        -0.22083051, -0.73694066]])

In [ ]:
std_xtest[:,rfe.support_]

array([[ 0.11047195, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
        -0.80392231, -1.33895882, -0.98477371, -1.24596637, -1.1004125 ,
        -0.02645355, -0.10295973, -0.88314594, -0.19600834,  0.7165901 ],
       [ 1.69022084,  1.94079022,  1.1110243 , -0.5955573 , -0.11909827,
        -0.44184077, -0.06993395,  0.14469886, -1.4063022 ,  0.66212855,
        -0.02645355, -0.10295973,  0.63068105, -0.79174039, -0.32164616],
       [-0.67940249, -0.51525404, -0.90007032, -0.5955573 , -0.11909827,
        -0.22788349, -0.05397137, -0.35226907,  0.39747589, -0.51164479,
        -0.02645355, -0.10295973, -0.19504277, -0.41940786,  0.09364835],
       [ 0.90034639, -0.51525404,  1.1110243 ,  1.21645747, -0.11909827,
         0.43044659,  0.21739244, -0.53298468,  0.23714006, -0.33670742,
        -0.02645355, -0.10295973, -0.47028404, -0.34494135,  1.33953186],
       [-1.46927694, -0.51525404, -0.90007032,  1.21645747, -0.11909827,
         0.9406524 ,  1.17514706,  0.55130899, 

In [ ]:
#With top 15 features
model.fit(std_xtrain[:,rfe.support_], y_train)
mean_absolute_error(y_test, model.predict(std_xtest[:,rfe.support_]))

2278.5602174488945

In [ ]:
model = Lasso(alpha = 0.05, positive = True, max_iter = 100000)

for num_selected_features in list(range(15,0,-1)):
    rfe = RFE(model, n_features_to_select = num_selected_features)
    rfe.fit(std_xtrain, y_train)
    model.fit(std_xtrain[:,rfe.support_], y_train)
    results.append(mean_absolute_error(y_test, model.predict(std_xtest[:,rfe.support_])))

In [ ]:
for j in range(len(results)):
    if(min(results) == results[j]):
        ind = j

#Best number of features
len(results) - ind

11

In [ ]:
rfe = RFE(model, n_features_to_select = 15)
rfe.fit(std_xtrain, y_train)
rfe.ranking_

array([ 1,  9,  8,  7,  1,  1,  6,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        3,  4,  5,  1, 10,  1,  2, 11])

In [ ]:
selected_features = rfe.support_

In [ ]:
selected_features

array([ True, False, False, False,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True, False, False])

In [ ]:
import numpy as np

# Assuming 'rfe' is the RFE object and 'std_xtrain' is a NumPy array
selected_features = rfe.support_

# Get the top 15 selected feature indices
top_15_indices = np.where(selected_features)[0][:15]

# Define a list of feature names
feature_names = [
    'symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg']

# Print the top 15 features
for index in top_15_indices:
    print(feature_names[index])


symboling
aspiration
num-of-doors
drive-wheels
engine-location
wheel-base
length
width
height
curb-weight
engine-type
num-of-cylinders
engine-size
compression-ratio
peak-rpm


In [ ]:
results

[2279.777309419742,
 2278.5602174488945,
 2279.019264764603,
 2276.4515878766297,
 2253.0245359808123,
 2249.645525737947,
 2267.8331546984487,
 2348.2759873849404,
 2349.307210625733,
 2391.459812029817,
 2369.9560747196674,
 2377.078804205228,
 2437.8043547574084,
 2329.9008771551034,
 2528.70558246239,
 2691.2108643464094]

In [ ]:
min(results)

2249.645525737947

In [ ]:
import numpy as np

# Assuming 'rfe' is the RFE object and 'std_xtrain' is a NumPy array
selected_features = rfe.support_

# Set the cutoff value for selecting features
cutoff_value = 0.9  # Adjust this value as needed

# Calculate the number of features to be selected based on the cutoff value
num_selected_features = int(np.sum(selected_features) * cutoff_value)

# Get the top selected feature indices
top_indices = np.argsort(rfe.ranking_)[:num_selected_features]

# Define a list of feature names corresponding to your dataset
feature_names = [
    'symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg']


# Print the selected features
for index in top_indices:
    print(feature_names[index])

symboling
peak-rpm
compression-ratio
engine-size
num-of-cylinders
engine-type
curb-weight
width
length
height
engine-location
drive-wheels
num-of-doors
